const HOROSCOPE_DATA = {
  aries: {
    code: "aries",
    name: "Aries",
    vn_name: "Bạch Dương",
    date: {
      form: { month: 3, day: 21 },
      to: { month: 4, day: 19 },
    },
    emoji: "♈",
    sign: "sheep",
    element: "fire",
    lucky_number: 7,
  },
  taurus: {
    code: "taurus",
    name: "Taurus",
    vn_name: "Kim Ngưu",
    date: {
      form: { month: 4, day: 20 },
      to: { month: 5, day: 20 },
    },
    emoji: "♉",
    sign: "bull",
    element: "earth",
    lucky_number: 6,
  },
  gemini: {
    code: "gemini",
    name: "Gemini",
    vn_name: "Song Tử",
    date: {
      form: { month: 5, day: 21 },
      to: { month: 6, day: 21 },
    },
    emoji: "♊",
    sign: "twins",
    element: "air",
    lucky_number: 5,
  },
  cancer: {
    code: "cancer",
    name: "Cancer",
    vn_name: "Cự Giải",
    date: {
      form: { month: 6, day: 22 },
      to: { month: 7, day: 22 },
    },
    emoji: "♋",
    sign: "crab",
    element: "water",
    lucky_number: 4,
  },
  leo: {
    code: "leo",
    name: "Leo",
    vn_name: "Sư Tử",
    date: {
      form: { month: 7, day: 23 },
      to: { month: 8, day: 22 },
    },
    emoji: "♌",
    sign: "lion",
    element: "fire",
    lucky_number: 3,
  },
  virgo: {
    code: "virgo",
    name: "Virgo",
    vn_name: "Xử Nữ",
    date: {
      form: { month: 8, day: 23 },
      to: { month: 9, day: 22 },
    },
    emoji: "♍",
    sign: "virgin",
    element: "earth",
    lucky_number: 2,
  },
  libra: {
    code: "libra",
    name: "Libra",
    vn_name: "Thiên Bình",
    date: {
      form: { month: 9, day: 23 },
      to: { month: 10, day: 23 },
    },
    emoji: "♎",
    sign: "scales",
    element: "air",
    lucky_number: 1,
  },
  scorpio: {
    code: "scorpio",
    name: "Scorpio",
    vn_name: "Thiên Yết",
    date: {
      form: { month: 10, day: 24 },
      to: { month: 11, day: 21 },
    },
    emoji: "♏",
    sign: "scorpion",
    element: "water",
    lucky_number: 8,
  },
  sagittarius: {
    code: "sagittarius",
    name: "Sagittarius",
    vn_name: "Nhân Mã",
    date: {
      form: { month: 11, day: 22 },
      to: { month: 12, day: 21 },
    },
    emoji: "♐",
    sign: "archer",
    element: "fire",
    lucky_number: 9,
  },
  capricorn: {
    code: "capricorn",
    name: "Capricorn",
    vn_name: "Ma Kết",
    date: {
      form: { month: 12, day: 22 },
      to: { month: 1, day: 19 },
    },
    emoji: "♑",
    sign: "goat",
    element: "earth",
    lucky_number: 10,
  },
  aquarius: {
    code: "aquarius",
    name: "Aquarius",
    vn_name: "Bảo Bình",
    date: {
      form: { month: 1, day: 20 },
      to: { month: 2, day: 18 },
    },
    emoji: "♒",
    sign: "water bearer",
    element: "air",
    lucky_number: 11,
  },
  pisces: {
    code: "pisces",
    name: "Pisces",
    vn_name: "Song Ngư",
    date: {
      form: { month: 2, day: 19 },
      to: { month: 3, day: 20 },
    },
    emoji: "♓",
    sign: "fish",
    element: "water",
    lucky_number: 12,
  },
};
